name: 'mifx'

services:
  app:
    image: mifx-apps:test
    ports:
      - "8080:80"
    volumes:
      - ./site:/var/www/html:ro
    networks:
      - mifx

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: admin_user        # Full access user
      POSTGRES_PASSWORD: admin_pass   # Password for full access user
      POSTGRES_DB: sre                # Initial database
      TZ: Asia/Jakarta                
    ports:
      - "5432:5432"                   # Map PostgreSQL port to host
    volumes:
      - ./pgdata:/var/lib/postgresql/data   # Persistent data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf # Custom config
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Initial SQL script
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    networks:
      - mifx

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: rizkyadnan23@gmail.com
      PGADMIN_DEFAULT_PASSWORD: rizkyadnan08
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - mifx

networks:
  mifx:
    driver: bridge
